SELECT 
    B.REST_ID,
    B.REST_NAME,
    B.FOOD_TYPE,
    B.FAVORITES,
    B.ADDRESS,
    ROUND(AVG(A.REVIEW_SCORE), 2) AS SCORE
FROM 
    REST_REVIEW A
INNER JOIN 
    REST_INFO B ON A.REST_ID = B.REST_ID
WHERE 
    B.ADDRESS LIKE '서울%'
GROUP BY 
    B.REST_ID, B.REST_NAME, B.FOOD_TYPE, B.FAVORITES, B.ADDRESS
ORDER BY 
    SCORE DESC, B.FAVORITES DESC;
